apiVersion: v1
kind: Service
metadata:
  name: estore
  namespace: bits-k8s-ns
  labels:
    app: estore
spec:
  selector:
    app: estore
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
