commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: bits-k8s-ns

resources:
  - namespace.yml
  # Individual apps
  - estore-k8s/estore-deployment.yml
  - estore-k8s/estore-service.yml
  - estore-k8s/estore-mysql.yml
  - invoice-k8s/invoice-deployment.yml
  - invoice-k8s/invoice-service.yml
  - invoice-k8s/invoice-mysql.yml
  - notification-k8s/notification-deployment.yml
  - notification-k8s/notification-service.yml
  - notification-k8s/notification-mongodb.yml
  # service discovery eureka/consul
  - registry-k8s/jhipster-registry.yml
  - registry-k8s/application-configmap.yml

patchesJson6902:
