apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: bits-k8s-ns
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: 8082
